language: php

php:
  - 7.2
  - 7.3

env:
  - LARAVEL_VERSION=^6.0
  - LARAVEL_VERSION=^7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - php vendor/bin/phpunit --coverage-text
